spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=JobPortalSystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Raj@12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.data.redis.url=redis://default:3kokq8e6v8XNSMYve9Hje52eSk6oWKCd@glass-quiet-zebra-16617.db.redis.io:19951

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jobsportalssystem@gmail.com
spring.mail.password=esii mrol cglp acso
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT Configuration
jwt.secret.key=TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

